### PR TITLE
MaLiLib + 1.17

### LINKED ISSUE #9: Cannot exit the config of a specific module
**Describe the bug**
I haven't figured out how to exit out of a module config screen without exiting the whole KronHUD config.

**To Reproduce**
1. Go to Mod Menu
2. Scroll to KronHUD and click on config button
3. Right click a module
4. Do something, like toggle it off
5. Press Esc to save/return
6. KronHUD config exits entirely 

**Expected behavior**
I expected to go back to previous screen, so I could edit the config of another module.

**Screenshots**
N/A

**Additional context**
KronHUD 1.1.1
MC 1.16.3
Fabric API 0.20.2 b 402

### LINKED ISSUE #15: Modules can still be clicked or moved when they are disabled.
**Describe the bug**
Modules can still be clicked or moved around when they are disabled, and I'm pretty sure this isn't intentional.

**Expected behavior**
Disabled modules should not be able to be clicked or moved.

### LINKED ISSUE #17: Crash when using mod menu to configure
**Describe the bug**
When using mod menu to configure the HUD, the moment you click configure button the game crashes

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the game with mod menu installed
2. Open mod menu on the title screen
3. Click the configure button
4. CRASH

**Expected behaviour**
KronHUD config opens

[crash-2020-10-29_17.14.16-client.txt](https://github.com/DarkKronicle/KronHUD/files/5460174/crash-2020-10-29_17.14.16-client.txt)

### LINKED ISSUE #27: 1.17 Update
**Describe what you would like**
greetings
update for mc 1.17

**Additional context**
https://i.imgur.com/bkxuRxr.png

### LINKED ISSUE #31: Are you gonna update to 1.17?
**Describe what you would like**
Are you gonna update this mod to 1.17.1?
**Additional context**
Add any other context or screenshots about the feature request here. (Is there something similar to this, is this already partially added...)

### PR DESCRIPTION
**Pull request by TheKodeToad**
Loads of people asked for 1.17. So I thought I'd include it in this pull request. It was initially just to add MaLiLib.

The code does get a big hacky in some places. MaLiLib has an annoying bug with colour, that requires a hack to use a custom colour class in the config. Without the hack, white appears slightly pink (feel free to call me picky).

The old config is automatically converted into the new version.

I would appreciate it if you could suggest a new version number, so it can be uploaded to CurseForge (at least if this is merged - it may be too big to properly review).

Changes:
- MaLiLib (like you suggested).
- 1.17 update (fixes #27 and fixes #31 (duplicate)).
- When pressing escape on a module config it goes back to the list (fixes #9).
- Fixes #17 (although it was already technically fixed).
- Fixes #15.
- Text shadow is now configurable.

### P.
**S.**

I'm _working_ on **the**

 `inconsistencies`
I may 

1. have
2. caused
3. .

Edit: They have been fixed now (hopefully).

[Here is a formatting issue I didn't cause](https://github.com/DarkKronicle/KronHUD/blame/master/README.md#L7).

### CODE REVIEW

**Comment by DarkKronicle** [comment]
Gonna change the version to 2.0.0 if that works.

**Comment by DarkKronicle** [comment]
Thank you so much for contributing! I'll check it out and get it on curseforge.

**Comment by DarkKronicle** [comment]
https://www.curseforge.com/minecraft/mc-mods/kronhud/files/3441441 (hopefully will get approved soon)

**Comment by DarkKronicle** [comment]
Do you have a discord?

**Comment by TheKodeToad** [comment]
Thank you for merging so quickly! It may have a few bugs but I tested on a few servers and it worked for me.



> Do you have a discord?

Unfortunately, not yet.

**Comment by TheKodeToad** [comment]
What's confusing you, @JackTGG?

**Pull request merged**
