### PR TITLE
Add more customisation and fix some bugs.

### LINKED ISSUE #10: Dynamic arrow count
**Describe what you would like**
I want to see the arrow count only when holding a bow or crossbow.

**Additional context**
Optionally hiding the arrow icon would be cool too (keeping just the count).

### LINKED ISSUE #16: Add an option to disable snapping

### LINKED ISSUE #22: Attack indicator doesn't show
Issue:
Attack indicator doesn't show when set to Crosshair

To Reproduce:
1) Download and install the mod for 1.16.4
2) Ensure that Attack indicator setting is set to 'Crosshair'
3) Hit with something that has a long recharge time, like an ax.

https://user-images.githubusercontent.com/63116788/107855280-4ceace00-6def-11eb-9b20-60ec59abf109.mp4

### LINKED ISSUE #23: It crashes game when the mod is configured outside a minecraft world.
The mod crashes the game when you try to configure it using mod menu while not loaded in a minecraft world.

**To Reproduce**
0. Do not be in a minecraft world
1. Go to mod menu
2. Configure KronHud

**Expected behavior**
Either it prevents that configuration when not in world or some menu configuration.

### PR DESCRIPTION
**Pull request by TheKodeToad**
Adds more customisation:
- Dynamic arrow counter (only visible when bow is held) (fixes #10).
- Toggleable background.
- Separate left and right button CPS.
- Keystrokes text colour.
- Attack indicator colour and the attack indicator itself (fixes #22).
- Disable snapping (fixes #16).

Also changes some of the text to be more user friendly (e.g. "PotionEffectsHUD" -> "Potion Effects"), fixes #23 and makes some HUDs wider to be the same width as the keystrokes HUD (screenshot in issue #5 shows why this would be useful).
I also stole a bit of Minecraft's code to make it possible to draw a rectangle using `float`s, because I couldn't think of  a better way.

Also, shall I open another pull request to use ClothConfig instead of Polish (like with AdvancedChat)? Polish looks nicer than ClothConfig in some ways, but it has some issues:
- Doesn't support "Gui Scale: Auto".
- Doesn't support narrator (probably a good thing, but some people actually use or need narrator).
- Doesn't support window resizing.
- Scrolling is slow.
- I use bulleted lists far too much (probably my issue).
- Doesn't support changing button's text (word be useful for toggle buttons). 

Some of these issues could be fixed, but in my opinion ClothConfig works fine and feels more consistent.

### CODE REVIEW

**Comment by DarkKronicle** [comment]
All the changes are looking nice! I do think that Polish isn't as 'polished' as it needs to be to stand in for a configuration (configs can be hard). I've now written 4 different types of configurations using/combining different API's. All of them have their different strengths, but the one that I think would be the best is using MaLiLib built in configuration. Unlike cloth, it allows you to customize anything easily and gives you a lot of control. It is more complex to implement, but it would probably be best for the long run.

Do you have any thoughts on it?

**Comment by TheKodeToad** [comment]
What do you want in the config that cannot be created with Cloth?

**Comment by TheKodeToad** [comment]
@DarkKronicle Is there anything else to change, or have you just not got round to merging?

**Comment by DarkKronicle** [comment]
Sorry, I've been pretty busy. I'll try to test this and merge it tomorrow.

**Comment by HiHi3690** [comment]
@DarkKronicle will you update the curse forge page with these new changes? I can't compile it on this pc.

**Comment by TheKodeToad** [comment]
@HiHi3690 Unfortunately, I can't find any file sharing websites that don't delete the files automatically. The version number should be updated first before uploading to CurseForge.

**Comment by jeffrgh** [comment]
Guys this latest version is not on CurseForge

**Comment by TheKodeToad** [comment]
Yep. I know.

**Pull request merged**
