### PR TITLE
update to 1.20.1

### LINKED ISSUE #144: Update to 1.20 & 1.20.1
Update to 1.20 & 1.20.1

### PR DESCRIPTION
**Pull request by moehreag**
- update dependencies
- the DarkKore version is local since it's not yet published yet.. This is going to need to be changed before a release.

- closes #144 
- depends on https://github.com/DarkKronicle/DarkKore/pull/6

### If you want to test this PR before https://github.com/DarkKronicle/DarkKore/pull/6 is merged:

- build DarkKore from https://github.com/DarkKronicle/DarkKore/pull/6 and place `DarkKore-0.3.5-1.20.1.jar` in `run/mods/`
- you should now be able to use the dev env normally and/or build the mod for testing.

### CODE REVIEW

**Review by TheKodeToad — APPROVED** [review]
LGTM (i'm just too fast :zap:!)

Btw, I think you might simply be able to use your commit hash instead since i think it may be using JitPack. Maybe the repo needs changing too? idk

**Comment by moehreag** [comment]
> LGTM (i'm just too fast zap!)
> 
> Btw, I think you might simply be able to use your commit hash instead since i think it may be using JitPack. Maybe the repo needs changing too? idk

It probably is using jitpack, but it doesn't seem like it builds artifacts for prs

**Comment by TheKodeToad** [comment]
image


https://discord.com/channels/817576132726620200/1112802443135303700/1121539905055637524
(via https://discord.quiltmc.org)

**Comment by moehreag** [comment]
> image
> 
> https://discord.com/channels/817576132726620200/1112802443135303700/1121539905055637524 (via https://discord.quiltmc.org)

iirc the new maven address wasn't in their readme yet when we did this which is why it isn't changed yet

**Comment by TheKodeToad** [comment]
I brought it up as I feel it's something which could be done in this pull request!

**Comment by moehreag** [comment]
KronHUD doesn't actually depend on Satin, DarkKore does: https://github.com/DarkKronicle/DarkKore/pull/6/commits/5b1068998ed9bae63ebb3977768530dab256db65

**Comment by TheKodeToad** [comment]
Ahh

:thinking: The maven URL is in KronHUD too, though

**Comment by moehreag** [comment]
> Ahh
> 
> thinking The maven URL is in KronHUD too, though

probably because of the transitive dependencies

**Pull request merged**
